### ISSUE TITLE
ForzaDSX expecting "C:\temp\DualSenseX\DualSenseX_PortNumber.txt" to exist, but it doesn't

### ISSUE THREAD

**Issue by dan-schales** [cosmii02/RacingDSX#13]
When attempting to use ForzaDSX with a fresh install of DSX via Steam (never installed previously), it fails to load due to the file `C:\temp\DualSenseX\DualSenseX_PortNumber.txt` missing. This results in a red status for UDP in DSX and no adaptive trigger feedback in Forza 5.

I fixed this by manually creating the `C:\temp\DualSenseX\` directories and copying the `DualSenseX_PortNumber.txt` that exists in the DSX install folder into it. Restarting DSX, ForzaDSX, and Forza 5 afterward resulted in the mod working beautifully.

I'm not sure how to best handle this (c# is not in my repertoire atm), but I found the path hard coded here:
https://github.com/cosmii02/ForzaDSX/blob/d29ac2ec2b618d6f7336a830fd780b3bfe42de4b/ForzaDSXWorker.cs#L425 Maybe it can be set in the `config` file or it can find the DSX install and point there automatically?

**Comment by cosmii02** [comment]
I should probably remove that as a variable overall... but currently waiting for dsx v3

**Comment by dan-schales** [comment]
Looking at Discord, quite a few people are struggling with this. If it's as easy as removing it and relying on the port number defined in the UI, then that seems like a quick win and would be a huge help for those of us that are running into this (I spent hours troubleshooting this).

The mod is great, btw! :D

**Comment by cosmii02** [comment]
@danisawesome V0.5.2 should fix the situation, can anyone check?

**Comment by dan-schales** [comment]
@cosmii02 Just tried it out and it works great! 🙌

I deleted the temp file created as a fix, made sure the previous version wasn't working (UDP red, no adaptive triggers), and then opened the new version and it immediately connected to DSX (UDP green, adaptive triggers working!).

Thanks so much for fixing this!

**Comment by ElyDooDoo** [comment]
@cosmii02 Works perfectly! Thanks for your efforts :)

**Comment by cosmii02** [comment]
Awesome... anyway the mod will soon get an overhaul of some sorts... soon:tm:
