### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by VelSilk** [cosmii02/RacingDSX#14]
I tried to do it according to the instructions, but it doesn't work.
Forza is not shown in "Window 8 AppContainer Loopback" Utility
I did everything else according to the instructions, registered the ip and port, even opened them in the firewall. 
In DSX, I also checked UDP in the settings. In DSX writes the red UDP status so it should be? 
![1](https://user-images.githubusercontent.com/124005344/218341477-f054655e-3c2d-4422-8409-54e668059981.PNG)
![21](https://user-images.githubusercontent.com/124005344/218341478-bc1455a3-fd8b-4480-a01b-6065ab6218c3.PNG)

**Comment by VelSilk** [comment]
I do not know what I did, but it worked.

**Comment by Divoney97** [comment]
please tell me how did you make it work?

**Comment by 6xrd** [comment]
> Скажите, пожалуйста, как вы заставили это работать?

I also had this problem and here's how I solved it. In DSX, I chose to emulate the controller "off". 

Then I opened the Big Pictures mode on Steam and launched FH5 through it. The game did not respond to my DS gamepad, I pressed the "PS" button on the DS gamepad. The menu opens. You need to select Controller Settings, and then select the controller settings again and turn on the input system via Steam. 

And everything worked for me. I hope this helps you too.

Так как, я из СНГ, напишу то, что я написал в переводчик. 

У меня тоже была такая проблема и вот как я ее решил. 

В DSX я выбрал эмуляцию контролера "выключено". Затем я открыл в Steam режим Big Pictures и запустил FH5 через него. Игра не реагировала на мой DS геймпад, я нажал кнопку "PS" на DS геймпаде. Открывается меню. Надо выбрать Настройки геймпада, а затем опять настройки геймпада и включить систему ввода через Steam. 

И у меня все заработало. Надеюсь это поможет и Вам.

**Comment by cosmii02** [comment]
Steam input is defo not the solution here..
