### ISSUE TITLE
Changing any value does not change anything

### ISSUE THREAD

**Issue by Quitomm** [cosmii02/RacingDSX#16]
If you change the intensity of the right trigger effect by at least 99, then it stops working altogether. The rest of the parameters have no effect. Triger finished off in the finger like crazy. Feels like it's going to fly off at the next turn

**Comment by cosmii02** [comment]
Any update on this? @Chaoseiro

**Comment by Chaoseiro** [comment]
Not yet, will manage to take a look this weekend finally. Sorry about the delay

**Comment by cosmii02** [comment]
#24 seems to have fixed it, RC1 is also released. Main release will be happening next week
