### ISSUE TITLE
Vibration with Adaptive triggers

### ISSUE THREAD

**Issue by TymekTM** [cosmii02/RacingDSX#17]
Is there any way to get both vibration and active triggers while playing? 

Would love to use this for more immersive experience

**Comment by Chaoseiro** [comment]
Please, check if vibrations are enabled in DSX! This mod only modifies the triggers, so every other feedback should work as configured in DSX

**Comment by TymekTM** [comment]
Somehow DSX disables vibrations every time I lunch it. Going with this to the DSX forum. Thanks
