### ISSUE TITLE
Not working on FH5

### ISSUE THREAD

**Issue by Juh4s** [cosmii02/RacingDSX#21]
I quadruple checked everything, data out is enabled, the IP is set to 127.0.0.1, port 5300, UDP is enabled in DSX, port 6969, DSX works by itself, as in enabling any trigger modes work, so no clue what the issue is, I tried the other ForzaDSX and that doesn't seem to be working either, both programs say they are fully connected to the game but the triggers are just normal, no resistance or anything

**Comment by cosmii02** [comment]
Honestly unsure, the mod worked for my fresh install last test, I don't have hw to test with rn either

**Comment by pastuh** [comment]
Not works because game can't detect PS Edge controller. If I switch to Xbox, I can control everything, but can't feel any vibration.

**Comment by cosmii02** [comment]
? Forza only works with xbox emulation anyway

**Comment by Juh4s** [comment]
> Not works because game can't detect PS Edge controller. If I switch to Xbox, I can control everything, but can't feel any vibration.

...I'm not using a Edge controller

**Comment by cosmii02** [comment]
The issue wouldn't be related to you having Edge or not

**Comment by LZAndy** [comment]
Doesn't work either, it work when the version of FH5 is 1.522.259.0，but it doesnt work when I use the latest version

**Comment by cosmii02** [comment]
> Doesn't work either, it work when the version of FH5 is 1.522.259.0，but it doesnt work when I use the latest version

I will have this checked later, ty for the info

**Comment by cookie9822** [comment]
same doesn't work either

**Comment by cookie9822** [comment]
> I quadruple checked everything, data out is enabled, the IP is set to 127.0.0.1, port 5300, UDP is enabled in DSX, port 6969, DSX works by itself, as in enabling any trigger modes work, so no clue what the issue is, I tried the other ForzaDSX and that doesn't seem to be working either, both programs say they are fully connected to the game but the triggers are just normal, no resistance or anything

exactly same problem with forza5 v1-583-19-0 newest version haptic feedback on ps5 controller with old or newest firmware doesn't work

**Comment by DeltaPy** [comment]
Newest version doesn't work. I will try to patch it myself.

**Comment by cosmii02** [comment]
Sorry about this, for unforeseen circumstances I forgot my ds5 at home and won't be back in the country for another month... anyone has ideas what broke the compatibility?

**Comment by cosmii02** [comment]
@DeltaPy Could you make a PR when you find the cause?

**Comment by DeltaPy** [comment]
> Sorry about this, for unforeseen circumstances I forgot my ds5 at home and won't be back in the country for another month... anyone has ideas what broke the compatibility?

My guess is that the formatting changed. If you leave the game paused, your program detects the current vehicle, etc. But after unpausing, it just hangs.

**Comment by DeltaPy** [comment]
@cosmii02 I found the problem, the latest version of ForzaDSX 0.5.4 works perfectly after building it from source but most of the people including me are using the 0.5.3 version which doesn't work. You just need to add the 0.5.4 version to releases.

**Comment by cosmii02** [comment]
Bruh, this was awkward..

**Comment by cosmii02** [comment]
Btw @DeltaPy Would you be able to test if forza 4 also works now

**Comment by DeltaPy** [comment]
@cosmii02 I don't own it.

**Comment by LZAndy** [comment]
still cant work,why?
DSX Connection: Forza Connection and Verbose Mode is already green, but it still dont work

**Comment by icimence** [comment]
My situation is that vibration feedback and adaptive triggers are both working normally, but the adaptive triggers are almost locked up, and adjusting the max resistance parameters doesn't seem to have any effect.

**Comment by cosmii02** [comment]
Tested yet again, both fh4 and fh5 work flawlessly
