### ISSUE TITLE
Version 0.55 Flashback

### ISSUE THREAD

**Issue by FantasyOwl** [cosmii02/RacingDSX#23]
Version 0.55, I can't open it, the CMD window recedes in seconds after double-clicking

Version Windows 11 Professional
Version 22H2
Installation date 2022/11/17
OS Version 22621.1848
Experience Windows Feature Experience Pack 1000.22642.1000.0

**Comment by raritytiks** [comment]
Could you open a command window?

Win-R, type cmd, command prompt window should appear.
![image](https://github.com/cosmii02/ForzaDSX/assets/15831108/a420c7cb-2ad6-4a67-981b-5c1ddd3d58e5)


Execute the forza exe from this terminal by pasting the entire file path. (your terminal will probably look black and white)
![image](https://github.com/cosmii02/ForzaDSX/assets/15831108/3780a643-0071-4017-aa95-4f7b8abda15d)

This way the box won't close when the program is done executing. Is there an error message?

**Comment by FantasyOwl** [comment]
![image](https://github.com/cosmii02/ForzaDSX/assets/86191035/8cace69e-7a5b-4bbe-ad29-e757126e47c8)

**Comment by FantasyOwl** [comment]
> 你能打开一个命令窗口吗？
> 
> Win-R，键入cmd，应出现命令提示符窗口。 ![图像](https://user-images.githubusercontent.com/15831108/246200191-a420c7cb-2ad6-4a67-981b-5c1ddd3d58e5.png)
> 
> 通过粘贴整个文件路径从此终端执行 forza exe。（您的终端可能看起来是黑白的） ![图像](https://user-images.githubusercontent.com/15831108/246200779-3780a643-0071-4017-aa95-4f7b8abda15d.png)
> 
> 这样，当程序完成执行时，该框不会关闭。是否有错误消息？

![image](https://github.com/cosmii02/ForzaDSX/assets/86191035/f6b92241-e75e-4885-933d-4496833efb11)

**Comment by raritytiks** [comment]
It seems that the problem is that you're missing the .NET 7 runtime files.

(Edit) Make sure you get the Desktop Runtime.

![image](https://github.com/cosmii02/ForzaDSX/assets/15831108/d99a42b4-2510-4eab-af8c-c480cd26d2e2)

**Comment by rxmzes** [comment]
> > 你能打开一个命令窗口吗？
> > Win-R，键入cmd，应出现命令提示符窗口。 ![图像](https://user-images.githubusercontent.com/15831108/246200191-a420c7cb-2ad6-4a67-981b-5c1ddd3d58e5.png)
> > 通过粘贴整个文件路径从此终端执行 forza exe。（您的终端可能看起来是黑白的） ![图像](https://user-images.githubusercontent.com/15831108/246200779-3780a643-0071-4017-aa95-4f7b8abda15d.png)
> > 这样，当程序完成执行时，该框不会关闭。是否有错误消息？
> 
> ![image](https://user-images.githubusercontent.com/86191035/246204177-f6b92241-e75e-4885-933d-4496833efb11.png)

(please check the edit in my reply)

**Comment by raritytiks** [comment]
Okay, wait. Do you already have it installed?

![image](https://github.com/cosmii02/ForzaDSX/assets/15831108/88f7c495-e850-49d9-bf0e-983f22a74223)

**Comment by raritytiks** [comment]
If 7.0.7 didn't work, maybe try 7.0.0  ...

![image](https://github.com/cosmii02/ForzaDSX/assets/15831108/d5cd9c24-f447-4b70-8e42-eb8e5251b9da)

**Comment by FantasyOwl** [comment]
> 如果 7.0.7 不起作用，也许尝试 7.0.0 ...
> 
> ![图像](https://user-images.githubusercontent.com/15831108/246209489-d5cd9c24-f447-4b70-8e42-eb8e5251b9da.png)

![image](https://github.com/cosmii02/ForzaDSX/assets/86191035/0152cefb-dc96-41be-9571-17359e4bfc21)

**Comment by FantasyOwl** [comment]
> > 如果 7.0.7 不起作用，也许尝试 7.0.0 ...
> > ![图像](https://user-images.githubusercontent.com/15831108/246209489-d5cd9c24-f447-4b70-8e42-eb8e5251b9da.png)
> 
> ![image](https://user-images.githubusercontent.com/86191035/246301256-0152cefb-dc96-41be-9571-17359e4bfc21.png)

Do I need to do a reboot after the installation is complete for it to take effect?

**Comment by cosmii02** [comment]
#24 0.5.6 will try to fix this issue, and once v3 releases it will use .net7 anyway so there won't be anymore issues, 0.5.6 will contain the runtime anyway for now to counter this
