### ISSUE TITLE
Forza4 dosen't work

### ISSUE THREAD

**Issue by Siri-1819** [cosmii02/RacingDSX#25]
I follow the steps but udp still shows red
And i didn't found forza4 in the loopback utility

**Comment by cosmii02** [comment]
Hopefully the issue went away for you after a restart, if not then reopen the issue and tag me

**Comment by wkkksss** [comment]
I can't found forza5 in the loopback utility even though I restarted for many times and udp still shows red. @cosmii02

**Comment by cosmii02** [comment]
Forza 5 shouldn't even need loopback, only forza 4 and older need that

**Comment by wkkksss** [comment]
> 

Then why is the udp still shows red? I've checked several times and everything is right.
