### ISSUE TITLE
left trigger

### ISSUE THREAD

**Issue by poiiiii** [cosmii02/RacingDSX#26]
The left trigger key is too heavy. Adjusting any value in the settings will directly disable the plugin

**Comment by cosmii02** [comment]
This is related to #16

**Comment by poiiiii** [comment]
I have adjusted all the options and the data cannot solve the problem of the left trigger being too hard at the beginning when driving in a straight line. Is there any solution? Otherwise, using this plugin can easily miss the braking point

**Comment by cosmii02** [comment]
@Chaoseiro uwu please

**Comment by poiiiii** [comment]
And the issue with Horizon 4 has now been inexplicably resolved. Version 5.5 can recognize and correctly trigger vibrations

**Comment by poiiiii** [comment]
After installing the script hooks and mods of RDR2 correctly, the UDP of Horizon 4 also worked inexplicably well and can now trigger normally. My friend on my end said, "There are two HID compliant game controllers in Device Manager, disable the one mapped to DSX, and then restart DSX, and the UDP will turn green." However, it seems that this problem cannot be solved very well. After restarting, there is a probability that the UDP will turn red again

**Comment by cosmii02** [comment]
You do have hidhide installed right?

**Comment by poiiiii** [comment]
yes

**Comment by poiiiii** [comment]
And there are also many people in my comments section who are troubled by the heavy brake trigger

**Comment by poiiiii** [comment]
I don't speak English, so when using translation software to provide feedback to you, there may be some sentences that I can't quite understand

**Comment by cosmii02** [comment]
@poiiiii https://github.com/cosmii02/ForzaDSX/releases/tag/latest-candidate
Can you try this version and tell me if it's better now

**Comment by poiiiii** [comment]
This version is perfect Thank you
