### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Marc-MMA** [cosmii02/RacingDSX#29]
I don't know how else to explain it, I've followed the tutorial to the letter, which isn't at all complex, and it has no effect, nothing happens, my dualsense continues to work as it did without your module...

- Forza 5
- Dualsense
- Windows 11
- DualSenseX (paid steam version)

Let me know if you need anything else...

Thanks

**Comment by Kreatifchk** [comment]
Exactly the same sitation only windows 10.

**Comment by cosmii02** [comment]
Couldn't diagnose issue/windows installation related issue. Open new issue if the issue persists on a new windows install
