### ISSUE TITLE
Forza Motorsport Support?

### ISSUE THREAD

**Issue by TheBacon00** [cosmii02/RacingDSX#30]
Hello,

I've attempted to set this up with Forza Motorsport (8) -- by all accounts I would think it would work since the telemetry output is configured the same as FH5 and FM7, however I'm unable to get it to work. The new Motorsport doesn't show up in the Loopback util, which could be part of the problem. The connection status for Forza is always red, so it seems like there's some sort of disconnect between the game and the utility. I'll keep trying to get this to work but was wondering if there is any "official" support yet.

Thanks! Great little app.

**Comment by dospaquetes** [comment]
Hello,

I'll second this issue, it doesn't work for me either.

**Comment by zchenak** [comment]
Can confirm Forza Motorsport does not work. It is checked in the Loopback util, but the connection status for Forza is always red. Maybe the telemetry structure is changed?

**Comment by zchenak** [comment]
It seems that the DASH packet lenght for FM8 is 331, different from 311 for FM7. DASH data is still from the 233rd to 311st byte though. Just FYI.

EDIT:
Tried to add Case 331 in AdjustToBufferType(int bufferLength), which has the same statements with Case 311, then both [forza-telemetry](https://github.com/austinbaccus/forza-telemetry) and [ForzaDualSense](https://github.com/patmagauran/ForzaDualSense) work with FM8.

**Comment by cosmii02** [comment]
#31 Thanks to @zchenak 
https://github.com/cosmii02/ForzaDSX/releases/tag/V0.5.7

**Comment by TheBacon00** [comment]
Thank you @zchenak !
