### ISSUE TITLE
ForzaDSX not recognising FM8

### ISSUE THREAD

**Issue by Itsum92** [cosmii02/RacingDSX#33]
I did everything in the description but forzaDSX only recognizes DSX but not FM8. Im playing on steam.

**Comment by TylerC161** [comment]
Same here.  I'm not getting any rumble either. I am running the GamePass version. DSX is showing red for the UDP connection. ForzaDSX though is showing green on Forza and Verbose. DSX is set as xbox 360 controller. Port in Forza is set to 5300. Data out is Car Dash format. Port in DSX is set to 6969. Both ports match respectively in ForzaDSX program.

Edit: Fixed. I needed to use Window 8 AppContainer Loopback Utility for Forza. All works well now.

**Comment by cire-cire-cire** [comment]
Same, also on steam. Ports are all set up correctly however ForzaDSX is giving me red for connection with FM8. Connects to DSX just fine, however.

**Comment by zchenak** [comment]
For the steam version, could you please confirm the process name of the Forza Motorsport? @cire-cire-cire @Itsum92  Go to task manager, right click on Forza Motorsport and select go to details

**Comment by cire-cire-cire** [comment]
Hey @zchenak, process name shows up as forza_steamworks_release_final.exe on task manager, I tried to fork a version to see if that was the issue but I quickly realized I have no idea how to use github lol. Thank you for looking in to this so fast

**Comment by zchenak** [comment]
@Itsum92 @cire-cire-cire please try [this fork](https://github.com/zchenak/ForzaDSX/tree/main) or equivalently the pull request [here](https://github.com/cosmii02/ForzaDSX/pull/34). Executable file in the publish folder

**Comment by cire-cire-cire** [comment]
Working perfect for me, thanks! @zchenak

**Comment by Itsum92** [comment]
It works! TYVM!
