### ISSUE TITLE
DSX 3

### ISSUE THREAD

**Issue by akominch** [cosmii02/RacingDSX#36]
Does this useful utility support DSX version 3? I tried it, it didn't work for me, after switching to 2 the adaptive triggers started working.

**Comment by cosmii02** [comment]
As of right now Dsx V3 support won't be coming unless someone else makes a PR that adds that when dsx v3 gets a mod API/interface

**Comment by Adaliciously** [comment]
@cosmii02 
![image](https://github.com/cosmii02/RacingDSX/assets/7670940/cf56dd0e-ebc8-4cea-b298-ff0e0fd59a6a)
DSX v3 has UDP now

**Comment by cosmii02** [comment]
At that time it was just a placeholder, however V3 will have v2 compatibility so it will work on day 1

**Comment by cosmii02** [comment]
dsx v3.1 compatibility tested and works. RacingDSX 0.6.2 will also release soon to address some serious issues in 0.6.1 and earlier
