### ISSUE TITLE
Cannot run application. 

### ISSUE THREAD

**Issue by MartL1980** [cosmii02/RacingDSX#39]
https://github.com/cosmii02/ForzaDSX/assets/155921798/8083f569-f445-45c8-b7b5-8196608d3d23

When i try to run the application, nothing happens.  Windows 11

**Comment by MartL1980** [comment]
Fixed. I had to unblock the application under Properties/General

**Comment by cosmii02** [comment]
Yeah, it might happen if you have some additional security settings enabled
