### ISSUE TITLE
Forza 5 doesn't work adaptive trigers 

### ISSUE THREAD

**Issue by Seryojik11** [cosmii02/RacingDSX#40]
hello everyone, I did everything to connect adaptive triggers, opened all ports, prescribed everything, but they do not work in forza 5, UDP is always red, although everything works well in cyberpunk, can someone help me find the reason?
Forza 5
Dualsense contoler 
Windows 11
DualSenseX (paid steam version) v 2.5
![1](https://github.com/cosmii02/ForzaDSX/assets/156612328/ec482f5c-bc17-4ed1-bf74-b37292f00750)
![2](https://github.com/cosmii02/ForzaDSX/assets/156612328/8a75cc55-aa9d-4fb0-a6e6-64351fdaea80)

**Comment by cosmii02** [comment]
It's been over a month now, hopefully the issue is gone. Everything works perfectly on a few testing machines so not sure what the issue was. Remake issue if it's still not gone
