### ISSUE TITLE
Linux / Steamdeck support?

### ISSUE THREAD

**Issue by CNR0706** [cosmii02/RacingDSX#47]
As far as I understand this project depends on DualSenseX which is problematic for desktop Linux and Steamdeck users because (as far as I can tell) it doesn't work on WINE / Proton and there is no native build available.

Linux has official support for Sony controllers (developed by Sony) and the DualSense is fully functional in some games already through Steam input. There is also this: https://github.com/Etaash-mathamsetty/trigger-control which might be helpful? Not sure though. So in theory it should be possible.

**Comment by cosmii02** [comment]
Is it worth it for the 3 linux users on the planet wanting this mod? I just don't think it's worth the time considering that this is a free project :(

**Comment by CNR0706** [comment]
That's understandable. I guess we'll have to wait for WINE to support DualSenseX then.

**Comment by cosmii02** [comment]
Considering that DSX will never come to linux, this mod won't either as it wouldn't make sense.
