### ISSUE TITLE
FH4 - triggers working but the LED is off

### ISSUE THREAD

**Issue by Dalevridge** [cosmii02/RacingDSX#48]
![image](https://github.com/cosmii02/RacingDSX/assets/55600578/01386fdf-b3fb-4ace-84e4-c9a830cfa862)

As seen above, the UDP is working and the triggers are vibrating as they should. But even though it doesn't let me change the LED settings, it doesn't change the color when driving in-game, it just stays off for some reason. I have RacingDSX settings on default so I'm not really sure where's the problem.

**Comment by Dalevridge** [comment]
The issue's getting even stranger - after a while when playing the LED turned white, stayed for about 3 minutes and then turned yellow, and as so it stays for now

**Comment by Dalevridge** [comment]
...now it's orange-red. Let's just say it changes in long seemingly random intervals. Really strange

**Comment by YSGJCian** [comment]
My situation is same as yours. If you only play FH4, you can try V0.5.5.

**Comment by cosmii02** [comment]
All of this is fixed by now :)
