### ISSUE TITLE
FH5 doesn't work with DSX v3.0.5

### ISSUE THREAD

**Issue by jordanbelinsky** [cosmii02/RacingDSX#51]
I followed all of the instructions but Forza Horizon 5 doesn't work. The app shows green for both connections and its enabled in firewall, but no feedback is felt in the triggers or haptics.

**Comment by Nuzair46** [comment]
Me too. only seems to be working with V2.

**Comment by cosmii02** [comment]
Will investigate when I find time 👀

**Comment by cosmii02** [comment]
Tested on a new windows installation and everything works perfectly, so idk why some of you might have issues

**Comment by Nuzair46** [comment]
I will try revert the settings in DSX3 to defaults and then try again and update here.

**Comment by Nuzair46** [comment]
Still no luck for me in a newly installed DSX v3 and default settings.
This is my settings in DSX changed other than default.
```
Incoming UDP, on, localhost:6969
Outgoing UDP, on localhost:6969
Controller running Native mode
```
Firewall and connection status🟢 

This same configuration is working for me in V2 so I don't this its related to any ports being blocked by firewall. but rather maybe DSX v3 failing to send the data to the controller. Its hard to know if UDP is working in v3 because there is no status that shows an active UDP connection.

**Comment by Nuzair46** [comment]
@cosmii02 Are you by any chance using DSX v3.1? The public release on steam is v3.0.5 which is what we are using. The v3.1 has the mod support according to paliverse on Discord which looks to be in private beta which you might have access to.

**Comment by cosmii02** [comment]
> @cosmii02 Are you by any chance using DSX v3.1? The public release on steam is v3.0.5 which is what we are using. The v3.1 has the mod support according to paliverse on Discord which looks to be in private beta which you might have access to.

My bad, I didn't read issue title properly. I thought you had issues on dsx v2. But yes I am on v3.1 but until it releases you should use v2 for mods

**Comment by Nuzair46** [comment]
@cosmii02 thanks for confirming. please update the readme as it says it supports v3.

**Comment by cosmii02** [comment]
Considering that v3.1 is now out and supports mods. This is no longer an issue :)
