### ISSUE TITLE
App do not start.

### ISSUE THREAD

**Issue by PoGoX2017** [cosmii02/RacingDSX#53]
![image](https://github.com/user-attachments/assets/e940a496-226c-455c-8d18-885ed8b566ba)
(error in polish)
I can't run app.  .NET 8.0 is instaled.
and yes i restarted pc after inatalation to be safe that all is good.  
But from good news older version works just fine. 😄

**Comment by cosmii02** [comment]
Can you try if latest RC version works?

**Comment by vDaarky** [comment]
I have the same problem but I don't receive any type of error window, the app simply doesn't start.
edit: (yes i have everything needed installed, and yes old versions works just fine)

**Comment by cosmii02** [comment]
> I have the same problem but I don't receive any type of error window, the app simply doesn't start. edit: (yes i have everything needed installed, and yes old versions works just fine)

Just double checking have you tried the latest RC version as well?

**Comment by vDaarky** [comment]
yes, I downloaded it 10 minutes ago

**Comment by vDaarky** [comment]
> > I have the same problem but I don't receive any type of error window, the app simply doesn't start. edit: (yes i have everything needed installed, and yes old versions works just fine)
> 
> Just double checking have you tried the latest RC version as well?

yes, I downloaded it 10 minutes ago

**Comment by vDaarky** [comment]
you mean this right?: https://github.com/cosmii02/RacingDSX/releases/tag/latest-candidate-12%2F01

**Comment by cosmii02** [comment]
Yes, the reason I ask is because RC versions are compiled with self contained .net while release versions are not

**Comment by vDaarky** [comment]
> Yes, the reason I ask is because RC versions are compiled with self contained .net while release versions are not

So, restarting the PC solved the problem with the RC starting without any issues. I tried to download the Release again, but it still doesn't work—the same problem as before. When trying to restart the RC, it stopped opening again. I tried to delete the official release, but it said that the file was open. I restarted the PC one last time because I couldn't find it in the task manager, and now it works. I guess I won't open the release file again, atm.

What could be causing this issue?

**Comment by PoGoX2017** [comment]
ok so RC version are starting up. But maybe i don't know how to use it with dirt raly 2.0. but maybe i will succed in making it work :)

**Comment by cosmii02** [comment]
@PoGoX2017 @vDaarky Try 0.6.4, that should fix the issues

**Comment by vDaarky** [comment]
> @PoGoX2017 @vDaarky Try 0.6.4, that should fix the issues

Yep, working just fine. Thanks
