### ISSUE TITLE
New function need: Add translation file support

### ISSUE THREAD

**Issue by CHN-STUDENT** [cosmii02/RacingDSX#9]
hi, i am a Chinese player who play forza5, and i use DSX and ForzaDSX when play games. But unlucky my english is so poor, i want to know how change trigger settings, I hope you can add translate file(like tips)and i try to know what it is then help translate, thanks!

**Comment by cosmii02** [comment]
Translation will be queued for v1.0 release, ty for the feedback

**Comment by cosmii02** [comment]
Minor update on this, delayed until further notice unless someone wants to implement and make a PR for it
